### ISSUE TITLE
Web 框架里怎么没有 Iris?

### ISSUE THREAD

**Issue by leiyang23** [yinggaozhen/awesome-go-cn#101]
在 web 框架里没收录 Iris

**Comment by yinggaozhen** [comment]
@leiyang23  
你好，本项目是awesome-go的中文翻译版，每天是从那边定时同步的。
**Iris** 在 [web-frameworks](https://github.com/avelino/awesome-go#web-frameworks) 栏目下确实不存在，如果可以的话，像官方提交之后并被 merge 之后，本项目会进行次日进行同步。

- 原项目是 : [https://github.com/avelino/awesome-go](https://github.com/avelino/awesome-go)
- Pull Requests传送门 : [https://github.com/avelino/awesome-go/pulls](https://github.com/avelino/awesome-go/pulls)
