### ISSUE TITLE
能不能对star数排个序，方便找重点

### ISSUE THREAD

**Issue by iamazy** [yinggaozhen/awesome-go-cn#20]

**Comment by yinggaozhen** [comment]
@iamazy  感谢你的issue，非常不错的建议~ 后续版本将考虑加入

**Comment by yinggaozhen** [comment]
@iamazy  hi，你好

排序功能我思考了一下 ，目前暂时还是先不做了，打算目前顺序上与英文文档保持一致~

根据你反馈的**重点不太好找的**问题，我将项目按照star进行了分级，目前分为了三个等级

- star > 5000
- star > 1000
- star > 100

希望此功能帮助你解决这个问题，目前文档已更新~

**Comment by iamazy** [comment]
这样也可以，蟹蟹啦！！！

**Comment by yinggaozhen** [comment]
不客气~
