### ISSUE TITLE
add json 

### ISSUE THREAD

**Issue by houseme** [yinggaozhen/awesome-go-cn#211]
https://github.com/json-iterator/go

**Comment by yinggaozhen** [comment]
**首先，非常感谢你的积极反馈~**

但是有点遗憾，目前本项目的定位是 [awesome-go](https://github.com/avelino/awesome-go) 的中文翻译版(已在本项目的README中提及)，目前暂时无法通过在本项目添加工程。你可以前往 awesome-go 提交 [Pull Requests](https://github.com/avelino/awesome-go/pulls)

如果合并成功，本项目会在一天以内进行翻译 + 同步~
