### ISSUE TITLE
【投稿】数据库类 ql

### ISSUE THREAD

**Issue by xiaqiubo** [yinggaozhen/awesome-go-cn#28]
[ql](https://github.com/cznic/ql)
[ql-doc](https://godoc.org/modernc.org/ql#pkg-files)
实现了一个纯 Go 嵌入式 SQL 数据库引擎。

**Comment by yinggaozhen** [comment]
您好~ 非常抱歉，这个项目是awesome-go的中文翻译版，所以暂时无法添加项目。
您可以前往 awesome-go 提交 PR ，https://github.com/avelino/awesome-go/pulls，如果合并成功，本项目会在一天以内进行翻译 + 同步~

**Comment by xiaqiubo** [comment]
Ok,没看清，还以为是个新项目🤭
