### ISSUE TITLE
是不是机器翻译的中文？如果这样，比较建议保留英文。

### ISSUE THREAD

**Issue by polaris1119** [yinggaozhen/awesome-go-cn#4]
首先，感谢增强 awesome-go，我也弄了一个，不过没正式放出来，看你弄了，我的也就不弄了，不重复劳动。

不过，提个意见，个人如果要翻译，得人工认真翻译，否则建议别翻译了。比如：

studygolang - The community of studygolang in China

翻译成了：studygolang - 中国学生群体 

醉了~

**Comment by yinggaozhen** [comment]
目前是前期机器翻译 + 后期人工润色，目前正在对机翻的项目校验纠错，我会尽快对机翻不合理的文本纠正

**Comment by yinggaozhen** [comment]
@polaris1119 由于此工程是我在本周三学习Go过程中遇到的问题．

工程完成从idea原型 -> 最终实现，再到周四晚上上线只有短短一天．期中相当多细节部分完成的都不尽人意，譬如您所提到的翻译部分，确实完成的非常**粗糙**:persevere::persevere:．

**接下来我将寻求我身边朋友的协助，一起对工程进行人工本土翻译，提升翻译质量．**:punch:

**Comment by yinggaozhen** [comment]
@polaris1119 另外，您issue中提到的studygolang翻译错误，我这边已经第一时间进行了修复，现已调整为**Go语言中文网**，另外同栏目下其他错误翻译我也一并进行了初步调整

**Comment by yinggaozhen** [comment]
目前已同时支持中英版~
