### ISSUE TITLE
ants 的描述翻译有误

### ISSUE THREAD

**Issue by moeyui1** [yinggaozhen/awesome-go-cn#479]
https://github.com/yinggaozhen/awesome-go-cn#goroutines

``` 
ants star:4420 一个高性能和低成本的goroutine池在围棋。
```

应当翻译成“一个高性能且低损耗的 goroutine 池”，来自ants项目的官方描述。

**Comment by yinggaozhen** [comment]
感谢你的反馈，已修复~
