### ISSUE TITLE
Casbin项目地址不正确

### ISSUE THREAD

**Issue by godcong** [yinggaozhen/awesome-go-cn#667]
项目指向的是一个fork地址：
https://github.com/hsluoyz/casbin
源地址因该是：
https://github.com/casbin/casbin

**Comment by yinggaozhen** [comment]
源项目[awesome-go](https://github.com/avelino/awesome-go)列表中casbin仓库为fork仓库，导致了镜像后的地址也是fork地址。
目前已在当前镜像地址中进行了替换，感谢反馈~

**Comment by godcong** [comment]
真迅速：）
